"""initial schema: 26 tables

Revision ID: e05529ef4abb
Revises:
Create Date: 2026-04-16 20:30:00.403848

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e05529ef4abb"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alarm_records",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("dev_number", sa.String(length=50), nullable=False),
        sa.Column("point_id", sa.BigInteger(), nullable=True),
        sa.Column("alarm_name", sa.String(length=100), nullable=True),
        sa.Column("alarm_msg", sa.String(length=255), nullable=True),
        sa.Column("alarm_value", sa.Double(), nullable=True),
        sa.Column("channels_sent", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("triggered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reset_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("usr_group", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alarm_records")),
    )
    op.create_index(
        "idx_alarm_records_dev_triggered",
        "alarm_records",
        ["dev_number", sa.literal_column("triggered_at DESC")],
        unique=False,
    )
    op.create_table(
        "device_templates",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("dev_type", sa.String(length=50), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_device_templates")),
    )
    op.create_table(
        "pay_orders_seen",
        sa.Column("out_trade_no", sa.String(length=50), nullable=False),
        sa.Column(
            "notified_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("out_trade_no", name=op.f("pk_pay_orders_seen")),
    )
    op.create_index(
        "ix_pay_orders_seen_notified_at_brin",
        "pay_orders_seen",
        ["notified_at"],
        unique=False,
        postgresql_using="brin",
    )
    op.create_table(
        "point_data_history",
        sa.Column("dev_number", sa.String(length=50), nullable=False),
        sa.Column("point_id", sa.BigInteger(), nullable=False),
        sa.Column("org_value", sa.Double(), nullable=True),
        sa.Column("rt_value", sa.Double(), nullable=True),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint(
            "dev_number", "point_id", "recorded_at", name=op.f("pk_point_data_history")
        ),
    )
    op.create_index(
        "ix_point_data_history_dev_number_point_id_recorded_at",
        "point_data_history",
        ["dev_number", "point_id", sa.literal_column("recorded_at DESC")],
        unique=False,
    )
    op.create_table(
        "point_data_realtime",
        sa.Column("dev_number", sa.String(length=50), nullable=False),
        sa.Column("point_id", sa.BigInteger(), nullable=False),
        sa.Column("org_value", sa.Double(), nullable=True),
        sa.Column("rt_value", sa.Double(), nullable=True),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("dev_number", "point_id", name=op.f("pk_point_data_realtime")),
        info={
            "postgresql_with": {
                "fillfactor": "70",
                "autovacuum_vacuum_scale_factor": "0.05",
                "autovacuum_analyze_scale_factor": "0.02",
                "autovacuum_vacuum_cost_limit": "1000",
                "autovacuum_vacuum_insert_scale_factor": "0.1",
            }
        },
    )
    op.create_table(
        "sim_cards",
        sa.Column("iccid", sa.String(length=50), nullable=False),
        sa.Column("msisdn", sa.String(length=20), nullable=True),
        sa.Column("card_type", sa.String(length=50), nullable=True),
        sa.Column("card_status", sa.SmallInteger(), nullable=False),
        sa.Column("service_months", sa.Integer(), nullable=True),
        sa.Column("data_amount", sa.Double(), nullable=True),
        sa.Column("total_data_amount", sa.Double(), nullable=True),
        sa.Column("open_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("active_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cost", sa.Double(), nullable=True),
        sa.Column("month_data", sa.Double(), nullable=True),
        sa.Column("remark", sa.String(length=255), nullable=True),
        sa.Column("usr_remark", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("iccid", name=op.f("pk_sim_cards")),
    )
    op.create_table(
        "soft_logs",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("level", sa.String(length=10), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("msg", sa.String(length=500), nullable=False),
        sa.Column("context", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("level IN ('WARN','ERROR','CRITICAL')", name=op.f("ck_soft_logs_level")),
        sa.CheckConstraint("source IN ('gw','api','worker')", name=op.f("ck_soft_logs_source")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_soft_logs")),
    )
    op.create_index(
        "ix_soft_logs_level_recorded_at",
        "soft_logs",
        ["level", sa.literal_column("recorded_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_soft_logs_source_recorded_at",
        "soft_logs",
        ["source", sa.literal_column("recorded_at DESC")],
        unique=False,
    )
    op.create_table(
        "user_control_actions",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("dev_number", sa.String(length=50), nullable=False),
        sa.Column("user_name", sa.String(length=50), nullable=False),
        sa.Column("action", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("cmd_id", sa.String(length=32), nullable=True),
        sa.Column("result", sa.String(length=20), nullable=True),
        sa.Column(
            "acted_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("usr_group", sa.String(length=50), nullable=False),
        sa.CheckConstraint(
            "(result = 'pending') = (completed_at IS NULL)",
            name=op.f("ck_user_control_actions_result_completed_consistency"),
        ),
        sa.CheckConstraint(
            "result IN ('pending','success','failed','timeout','cancelled')",
            name=op.f("ck_user_control_actions_result"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_control_actions")),
        sa.UniqueConstraint("cmd_id", name=op.f("uq_user_control_actions_cmd_id")),
    )
    op.create_index(
        "idx_user_control_actions_dev_acted",
        "user_control_actions",
        ["dev_number", sa.literal_column("acted_at DESC")],
        unique=False,
    )
    op.create_index(
        "idx_user_control_actions_user_acted",
        "user_control_actions",
        ["user_name", sa.literal_column("acted_at DESC")],
        unique=False,
    )
    op.create_table(
        "user_emails",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("phone_number", sa.String(length=20), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_emails")),
    )
    op.create_table(
        "waveform_history",
        sa.Column("dev_number", sa.String(length=50), nullable=False),
        sa.Column("point_id", sa.BigInteger(), nullable=False),
        sa.Column("data_array", sa.LargeBinary(), nullable=False),
        sa.Column("tz_data_array", sa.LargeBinary(), nullable=True),
        sa.Column("sample_time_decisec", sa.SmallInteger(), nullable=False),
        sa.Column("packet_count", sa.SmallInteger(), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint(
            "dev_number", "point_id", "recorded_at", name=op.f("pk_waveform_history")
        ),
    )
    op.create_table(
        "wx_groups",
        sa.Column("usr_group", sa.String(length=50), nullable=False),
        sa.Column("appid", sa.String(length=50), nullable=True),
        sa.Column("appsecret", sa.String(length=100), nullable=True),
        sa.Column("token", sa.String(length=200), nullable=True),
        sa.Column("token_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("template_id", sa.String(length=50), nullable=True),
        sa.Column("company_name", sa.String(length=100), nullable=True),
        sa.Column("sys_title", sa.String(length=100), nullable=True),
        sa.Column("remark", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("usr_group", name=op.f("pk_wx_groups")),
    )
    op.create_table(
        "alarm_outbox",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("alarm_id", sa.BigInteger(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("published", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["alarm_id"], ["alarm_records.id"], name=op.f("fk_alarm_outbox_alarm_id_alarm_records")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alarm_outbox")),
    )
    op.create_index(
        "idx_alarm_outbox_unpublished",
        "alarm_outbox",
        ["published", "created_at"],
        unique=False,
        postgresql_where="published = false",
    )
    op.create_table(
        "pay_orders",
        sa.Column("out_trade_no", sa.String(length=50), nullable=False),
        sa.Column("openid", sa.String(length=100), nullable=False),
        sa.Column("usr_group", sa.String(length=50), nullable=False),
        sa.Column("total_fee", sa.Integer(), nullable=False),
        sa.Column("body", sa.String(length=255), nullable=True),
        sa.Column("pay_state", sa.String(length=20), server_default="pending", nullable=False),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("refund_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(pay_state = 'paid') = (paid_at IS NOT NULL)",
            name=op.f("ck_pay_orders_paid_biconditional"),
        ),
        sa.CheckConstraint(
            "pay_state IN ('pending','paid','failed','refund','cancelled','expired')",
            name=op.f("ck_pay_orders_pay_state"),
        ),
        sa.CheckConstraint(
            "refund_at IS NULL OR paid_at IS NOT NULL",
            name=op.f("ck_pay_orders_refund_requires_paid"),
        ),
        sa.CheckConstraint(
            "refund_at IS NULL OR refund_at >= paid_at",
            name=op.f("ck_pay_orders_refund_after_paid"),
        ),
        sa.CheckConstraint("total_fee >= 0", name=op.f("ck_pay_orders_total_fee_nonneg")),
        sa.ForeignKeyConstraint(
            ["usr_group"],
            ["wx_groups.usr_group"],
            name=op.f("fk_pay_orders_usr_group_wx_groups"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("out_trade_no", name=op.f("pk_pay_orders")),
    )
    op.create_index(
        "ix_pay_orders_openid_created",
        "pay_orders",
        ["openid", sa.literal_column("created_at DESC")],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        "ix_pay_orders_pending_created",
        "pay_orders",
        ["created_at"],
        unique=False,
        postgresql_where=sa.text("pay_state = 'pending' AND deleted_at IS NULL"),
    )
    op.create_index(
        "ix_pay_orders_usr_group_created",
        "pay_orders",
        ["usr_group", sa.literal_column("created_at DESC")],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "user_login_records",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_name", sa.String(length=50), nullable=False),
        sa.Column(
            "logged_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("ip_addr", postgresql.INET(), nullable=False),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column("success", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("usr_group", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["usr_group"],
            ["wx_groups.usr_group"],
            name=op.f("fk_user_login_records_usr_group_wx_groups"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_login_records")),
    )
    op.create_index(
        "ix_user_login_records_ip_fail",
        "user_login_records",
        ["ip_addr", sa.literal_column("logged_at DESC")],
        unique=False,
        postgresql_where=sa.text("NOT success"),
    )
    op.create_index(
        "ix_user_login_records_user_name_logged_at",
        "user_login_records",
        ["user_name", sa.literal_column("logged_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_user_login_records_usr_group_logged_at",
        "user_login_records",
        ["usr_group", sa.literal_column("logged_at DESC")],
        unique=False,
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_name", sa.String(length=50), nullable=False),
        sa.Column("password_hash", sa.String(length=100), nullable=False),
        sa.Column("login_name", sa.String(length=50), nullable=True),
        sa.Column("group_company", sa.String(length=100), nullable=True),
        sa.Column("company", sa.String(length=100), nullable=True),
        sa.Column("department", sa.String(length=100), nullable=True),
        sa.Column("authority", sa.String(length=20), nullable=False),
        sa.Column("control_authority", sa.SmallInteger(), nullable=False),
        sa.Column("sys_name", sa.String(length=50), nullable=True),
        sa.Column("usr_group", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "authority IN ('Administrators','GroupCompany','Company','User')",
            name=op.f("ck_users_authority"),
        ),
        sa.CheckConstraint(
            "user_name ~ '^1[3-9][0-9]{9}$' OR user_name ~ '^[a-zA-Z][a-zA-Z0-9_]{3,29}$'",
            name=op.f("ck_users_user_name_format"),
        ),
        sa.ForeignKeyConstraint(
            ["usr_group"], ["wx_groups.usr_group"], name=op.f("fk_users_usr_group_wx_groups")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("user_name", name=op.f("uq_users_user_name")),
    )
    op.create_index("idx_users_tenant", "users", ["usr_group"], unique=False)
    op.create_table(
        "devices",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("dev_number", sa.String(length=50), nullable=False),
        sa.Column("dev_ser_number", sa.String(length=50), nullable=False),
        sa.Column("iccid", sa.String(length=50), nullable=True),
        sa.Column("dev_name", sa.String(length=100), nullable=True),
        sa.Column("dev_type", sa.String(length=50), nullable=True),
        sa.Column("modbus_addr", sa.SmallInteger(), nullable=False),
        sa.Column("baud_rate", sa.Integer(), nullable=True),
        sa.Column("group_company", sa.String(length=100), nullable=True),
        sa.Column("company", sa.String(length=100), nullable=True),
        sa.Column("department", sa.String(length=100), nullable=True),
        sa.Column("administrators", sa.String(length=50), nullable=True),
        sa.Column("dev_ip", postgresql.INET(), nullable=True),
        sa.Column("code_file", sa.String(length=255), nullable=True),
        sa.Column("code_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("update_interval_decisec", sa.Integer(), nullable=False),
        sa.Column("last_call_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_back_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("loss_count", sa.Integer(), nullable=False),
        sa.Column("is_online", sa.Boolean(), nullable=False),
        sa.Column("last_state", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("update_flag", sa.Integer(), nullable=False),
        sa.Column("usr_group", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "baud_rate IN (9600, 19200, 38400, 57600, 115200)", name=op.f("ck_devices_baud_rate")
        ),
        sa.CheckConstraint("modbus_addr BETWEEN 1 AND 247", name=op.f("ck_devices_modbus_addr")),
        sa.CheckConstraint(
            "update_interval_decisec BETWEEN 10 AND 1000", name=op.f("ck_devices_poll_interval")
        ),
        sa.ForeignKeyConstraint(
            ["administrators"], ["users.user_name"], name=op.f("fk_devices_administrators_users")
        ),
        sa.ForeignKeyConstraint(
            ["usr_group"], ["wx_groups.usr_group"], name=op.f("fk_devices_usr_group_wx_groups")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_devices")),
        sa.UniqueConstraint("dev_number", name=op.f("uq_devices_dev_number")),
        sa.UniqueConstraint("dev_ser_number", "iccid", name=op.f("uq_devices_ser_iccid")),
    )
    op.create_index("idx_devices_admin", "devices", ["administrators"], unique=False)
    op.create_index(
        "idx_devices_online",
        "devices",
        ["is_online"],
        unique=False,
        postgresql_where="deleted_at IS NULL",
    )
    op.create_index("idx_devices_tenant", "devices", ["usr_group"], unique=False)
    op.create_table(
        "maintain_actions",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("action_uuid", sa.String(length=26), nullable=False),
        sa.Column("plan_id", sa.BigInteger(), nullable=False),
        sa.Column("dev_number", sa.String(length=50), nullable=False),
        sa.Column(
            "acted_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("user_name", sa.String(length=50), nullable=False),
        sa.Column("note", sa.String(length=1000), nullable=True),
        sa.Column("usr_group", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_name"],
            ["users.user_name"],
            name=op.f("fk_maintain_actions_user_name_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["usr_group"],
            ["wx_groups.usr_group"],
            name=op.f("fk_maintain_actions_usr_group_wx_groups"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_maintain_actions")),
        sa.UniqueConstraint("action_uuid", name=op.f("uq_maintain_actions_action_uuid")),
    )
    op.create_index(
        "ix_maintain_actions_dev_acted",
        "maintain_actions",
        ["dev_number", sa.literal_column("acted_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_maintain_actions_plan_acted",
        "maintain_actions",
        ["plan_id", sa.literal_column("acted_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_maintain_actions_user_acted",
        "maintain_actions",
        ["user_name", sa.literal_column("acted_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_maintain_actions_usr_group", "maintain_actions", ["usr_group"], unique=False
    )
    op.create_table(
        "scene_pages",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("owner_user_name", sa.String(length=50), nullable=False),
        sa.Column("page_name", sa.String(length=100, collation="zh-x-icu"), nullable=False),
        sa.Column("sonpage_name", sa.String(length=100, collation="zh-x-icu"), nullable=True),
        sa.Column("sonpage_pic", sa.String(length=500), nullable=True),
        sa.Column("pos_x", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("pos_y", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("radius", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column("usr_group", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("pos_x BETWEEN -1000000 AND 1000000", name=op.f("ck_scene_pages_pos_x")),
        sa.CheckConstraint("pos_y BETWEEN -1000000 AND 1000000", name=op.f("ck_scene_pages_pos_y")),
        sa.CheckConstraint("radius BETWEEN 0.01 AND 100000", name=op.f("ck_scene_pages_radius")),
        sa.ForeignKeyConstraint(
            ["owner_user_name"],
            ["users.user_name"],
            name=op.f("fk_scene_pages_owner_user_name_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["usr_group"],
            ["wx_groups.usr_group"],
            name=op.f("fk_scene_pages_usr_group_wx_groups"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scene_pages")),
    )
    op.create_index("ix_scene_pages_owner", "scene_pages", ["owner_user_name"], unique=False)
    op.create_index("ix_scene_pages_usr_group", "scene_pages", ["usr_group"], unique=False)
    op.create_index(
        "ux_scene_pages_owner_page_name",
        "scene_pages",
        ["usr_group", "owner_user_name", "page_name"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "user_phone_numbers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_name", sa.String(length=50), nullable=False),
        sa.Column("phone_number", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_name"],
            ["users.user_name"],
            name=op.f("fk_user_phone_numbers_user_name_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_phone_numbers")),
    )
    op.create_table(
        "user_wx_bindings",
        sa.Column("openid", sa.String(length=100), nullable=False),
        sa.Column("user_name", sa.String(length=50), nullable=False),
        sa.Column("usr_group", sa.String(length=50), nullable=False),
        sa.Column("bound_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_name"],
            ["users.user_name"],
            name=op.f("fk_user_wx_bindings_user_name_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("openid", name=op.f("pk_user_wx_bindings")),
    )
    op.create_table(
        "device_points",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("dev_number", sa.String(length=50), nullable=False),
        sa.Column("point_name", sa.String(length=100), nullable=False),
        sa.Column("user_point_name", sa.String(length=100), nullable=True),
        sa.Column("point_number", sa.Integer(), nullable=False),
        sa.Column("fun_code", sa.SmallInteger(), nullable=False),
        sa.Column("dev_addr", sa.SmallInteger(), nullable=False),
        sa.Column("r_bit", sa.SmallInteger(), nullable=True),
        sa.Column("value_type", sa.String(length=20), nullable=False),
        sa.Column("point_unit", sa.String(length=20), nullable=True),
        sa.Column("point_ratio", sa.Double(), nullable=False),
        sa.Column("point_offset", sa.Double(), nullable=False),
        sa.Column("user_ratio", sa.Double(), nullable=False),
        sa.Column("user_point_offset", sa.Double(), nullable=False),
        sa.Column("min_value", sa.Double(), nullable=True),
        sa.Column("max_value", sa.Double(), nullable=True),
        sa.Column("show", sa.SmallInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("fun_code IN (1,2,3,4)", name=op.f("ck_device_points_fun_code")),
        sa.CheckConstraint(
            "point_number BETWEEN 0 AND 65535", name=op.f("ck_device_points_point_number")
        ),
        sa.ForeignKeyConstraint(
            ["dev_number"],
            ["devices.dev_number"],
            name=op.f("fk_device_points_dev_number_devices"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_device_points")),
    )
    op.create_index("idx_points_dev", "device_points", ["dev_number"], unique=False)
    op.create_table(
        "device_static_data",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("dev_number", sa.String(length=50), nullable=False),
        sa.Column("base_msg_name", sa.String(length=100), nullable=False),
        sa.Column("base_msg_value", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["dev_number"],
            ["devices.dev_number"],
            name=op.f("fk_device_static_data_dev_number_devices"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_device_static_data")),
    )
    op.create_table(
        "maintain_plans",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("dev_number", sa.String(length=50), nullable=False),
        sa.Column("plan_name", sa.String(length=100, collation="zh-x-icu"), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("interval_days", sa.Integer(), nullable=False),
        sa.Column("next_due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("enable", sa.Boolean(), nullable=False),
        sa.Column("usr_group", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "next_due_at >= created_at - INTERVAL '1 minute'",
            name=op.f("ck_maintain_plans_next_due_after_created"),
        ),
        sa.CheckConstraint(
            "interval_days BETWEEN 1 AND 3650", name=op.f("ck_maintain_plans_interval_days")
        ),
        sa.ForeignKeyConstraint(
            ["dev_number"],
            ["devices.dev_number"],
            name=op.f("fk_maintain_plans_dev_number_devices"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["usr_group"],
            ["wx_groups.usr_group"],
            name=op.f("fk_maintain_plans_usr_group_wx_groups"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_maintain_plans")),
    )
    op.create_index("ix_maintain_plans_dev_number", "maintain_plans", ["dev_number"], unique=False)
    op.create_index(
        "ix_maintain_plans_next_due_active",
        "maintain_plans",
        ["next_due_at"],
        unique=False,
        postgresql_where=sa.text("enable = true AND deleted_at IS NULL"),
    )
    op.create_index("ix_maintain_plans_usr_group", "maintain_plans", ["usr_group"], unique=False)
    op.create_index(
        "ux_maintain_plans_dev_plan_name",
        "maintain_plans",
        ["dev_number", "plan_name"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "scene_views",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("scene_page_id", sa.BigInteger(), nullable=False),
        sa.Column("owner_user_name", sa.String(length=50), nullable=False),
        sa.Column("company", sa.String(length=100), nullable=True),
        sa.Column("department", sa.String(length=100), nullable=True),
        sa.Column("dev_number", sa.String(length=50), nullable=False),
        sa.Column("pos_x", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("pos_y", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("radius", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column("usr_group", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("pos_x BETWEEN -1000000 AND 1000000", name=op.f("ck_scene_views_pos_x")),
        sa.CheckConstraint("pos_y BETWEEN -1000000 AND 1000000", name=op.f("ck_scene_views_pos_y")),
        sa.CheckConstraint("radius BETWEEN 0.01 AND 100000", name=op.f("ck_scene_views_radius")),
        sa.ForeignKeyConstraint(
            ["dev_number"],
            ["devices.dev_number"],
            name=op.f("fk_scene_views_dev_number_devices"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_name"],
            ["users.user_name"],
            name=op.f("fk_scene_views_owner_user_name_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["scene_page_id"],
            ["scene_pages.id"],
            name=op.f("fk_scene_views_scene_page_id_scene_pages"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["usr_group"],
            ["wx_groups.usr_group"],
            name=op.f("fk_scene_views_usr_group_wx_groups"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scene_views")),
    )
    op.create_index("ix_scene_views_dev_number", "scene_views", ["dev_number"], unique=False)
    op.create_index("ix_scene_views_owner", "scene_views", ["owner_user_name"], unique=False)
    op.create_index("ix_scene_views_page_id", "scene_views", ["scene_page_id"], unique=False)
    op.create_index("ix_scene_views_usr_group", "scene_views", ["usr_group"], unique=False)
    op.create_index(
        "ux_scene_views_page_dev",
        "scene_views",
        ["scene_page_id", "dev_number"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "timing_plans",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("dev_number", sa.String(length=50), nullable=False),
        sa.Column("action_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("action", sa.Integer(), nullable=False),
        sa.Column("repetition", sa.Integer(), nullable=False),
        sa.Column("enable", sa.Boolean(), nullable=False),
        sa.Column("update_flag", sa.SmallInteger(), nullable=False),
        sa.Column("usr_group", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["dev_number"],
            ["devices.dev_number"],
            name=op.f("fk_timing_plans_dev_number_devices"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["usr_group"],
            ["wx_groups.usr_group"],
            name=op.f("fk_timing_plans_usr_group_wx_groups"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_timing_plans")),
    )
    op.create_index(
        "ix_timing_plans_dev_action", "timing_plans", ["dev_number", "action_at"], unique=False
    )
    op.create_index(
        "ix_timing_plans_due",
        "timing_plans",
        ["action_at"],
        unique=False,
        postgresql_where=sa.text("enable = true AND deleted_at IS NULL"),
    )
    op.create_index("ix_timing_plans_usr_group", "timing_plans", ["usr_group"], unique=False)
    op.create_table(
        "device_waring_cfgs",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("dev_number", sa.String(length=50), nullable=False),
        sa.Column("point_id", sa.BigInteger(), nullable=False),
        sa.Column("reg_bit", sa.SmallInteger(), nullable=True),
        sa.Column("alarm_name", sa.String(length=100), nullable=False),
        sa.Column("alarm_type", sa.String(length=4), nullable=False),
        sa.Column("limit_value", sa.Double(), nullable=False),
        sa.Column("relation_point_id", sa.BigInteger(), nullable=True),
        sa.Column("relation_reg_bit", sa.SmallInteger(), nullable=True),
        sa.Column("relation_alarm_type", sa.String(length=4), nullable=True),
        sa.Column("relation_limit_value", sa.Double(), nullable=True),
        sa.Column("enable", sa.Boolean(), nullable=False),
        sa.Column("phone_alarm", sa.Integer(), nullable=False),
        sa.Column("reset_remind", sa.Boolean(), nullable=False),
        sa.Column("dev_sync_flag", sa.SmallInteger(), nullable=False),
        sa.Column("waring_flag", sa.Boolean(), nullable=False),
        sa.Column("alarm_msg", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "'NaN' != limit_value::text AND 'Infinity' != abs(limit_value)::text",
            name=op.f("ck_device_waring_cfgs_limit_value"),
        ),
        sa.CheckConstraint(
            "alarm_type IN ('>','<','=','!=','LX')", name=op.f("ck_device_waring_cfgs_alarm_type")
        ),
        sa.ForeignKeyConstraint(
            ["dev_number"],
            ["devices.dev_number"],
            name=op.f("fk_device_waring_cfgs_dev_number_devices"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["point_id"],
            ["device_points.id"],
            name=op.f("fk_device_waring_cfgs_point_id_device_points"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["relation_point_id"],
            ["device_points.id"],
            name=op.f("fk_device_waring_cfgs_relation_point_id_device_points"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_device_waring_cfgs")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("device_waring_cfgs")
    op.drop_index("ix_timing_plans_usr_group", table_name="timing_plans")
    op.drop_index(
        "ix_timing_plans_due",
        table_name="timing_plans",
        postgresql_where=sa.text("enable = true AND deleted_at IS NULL"),
    )
    op.drop_index("ix_timing_plans_dev_action", table_name="timing_plans")
    op.drop_table("timing_plans")
    op.drop_index(
        "ux_scene_views_page_dev",
        table_name="scene_views",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index("ix_scene_views_usr_group", table_name="scene_views")
    op.drop_index("ix_scene_views_page_id", table_name="scene_views")
    op.drop_index("ix_scene_views_owner", table_name="scene_views")
    op.drop_index("ix_scene_views_dev_number", table_name="scene_views")
    op.drop_table("scene_views")
    op.drop_index(
        "ux_maintain_plans_dev_plan_name",
        table_name="maintain_plans",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index("ix_maintain_plans_usr_group", table_name="maintain_plans")
    op.drop_index(
        "ix_maintain_plans_next_due_active",
        table_name="maintain_plans",
        postgresql_where=sa.text("enable = true AND deleted_at IS NULL"),
    )
    op.drop_index("ix_maintain_plans_dev_number", table_name="maintain_plans")
    op.drop_table("maintain_plans")
    op.drop_table("device_static_data")
    op.drop_index("idx_points_dev", table_name="device_points")
    op.drop_table("device_points")
    op.drop_table("user_wx_bindings")
    op.drop_table("user_phone_numbers")
    op.drop_index(
        "ux_scene_pages_owner_page_name",
        table_name="scene_pages",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index("ix_scene_pages_usr_group", table_name="scene_pages")
    op.drop_index("ix_scene_pages_owner", table_name="scene_pages")
    op.drop_table("scene_pages")
    op.drop_index("ix_maintain_actions_usr_group", table_name="maintain_actions")
    op.drop_index("ix_maintain_actions_user_acted", table_name="maintain_actions")
    op.drop_index("ix_maintain_actions_plan_acted", table_name="maintain_actions")
    op.drop_index("ix_maintain_actions_dev_acted", table_name="maintain_actions")
    op.drop_table("maintain_actions")
    op.drop_index("idx_devices_tenant", table_name="devices")
    op.drop_index("idx_devices_online", table_name="devices", postgresql_where="deleted_at IS NULL")
    op.drop_index("idx_devices_admin", table_name="devices")
    op.drop_table("devices")
    op.drop_index("idx_users_tenant", table_name="users")
    op.drop_table("users")
    op.drop_index("ix_user_login_records_usr_group_logged_at", table_name="user_login_records")
    op.drop_index("ix_user_login_records_user_name_logged_at", table_name="user_login_records")
    op.drop_index(
        "ix_user_login_records_ip_fail",
        table_name="user_login_records",
        postgresql_where=sa.text("NOT success"),
    )
    op.drop_table("user_login_records")
    op.drop_index(
        "ix_pay_orders_usr_group_created",
        table_name="pay_orders",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(
        "ix_pay_orders_pending_created",
        table_name="pay_orders",
        postgresql_where=sa.text("pay_state = 'pending' AND deleted_at IS NULL"),
    )
    op.drop_index(
        "ix_pay_orders_openid_created",
        table_name="pay_orders",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_table("pay_orders")
    op.drop_index(
        "idx_alarm_outbox_unpublished",
        table_name="alarm_outbox",
        postgresql_where="published = false",
    )
    op.drop_table("alarm_outbox")
    op.drop_table("wx_groups")
    op.drop_table("waveform_history")
    op.drop_table("user_emails")
    op.drop_index("idx_user_control_actions_user_acted", table_name="user_control_actions")
    op.drop_index("idx_user_control_actions_dev_acted", table_name="user_control_actions")
    op.drop_table("user_control_actions")
    op.drop_index("ix_soft_logs_source_recorded_at", table_name="soft_logs")
    op.drop_index("ix_soft_logs_level_recorded_at", table_name="soft_logs")
    op.drop_table("soft_logs")
    op.drop_table("sim_cards")
    op.drop_table("point_data_realtime")
    op.drop_index(
        "ix_point_data_history_dev_number_point_id_recorded_at", table_name="point_data_history"
    )
    op.drop_table("point_data_history")
    op.drop_index(
        "ix_pay_orders_seen_notified_at_brin", table_name="pay_orders_seen", postgresql_using="brin"
    )
    op.drop_table("pay_orders_seen")
    op.drop_table("device_templates")
    op.drop_index("idx_alarm_records_dev_triggered", table_name="alarm_records")
    op.drop_table("alarm_records")
    # ### end Alembic commands ###
